packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Upgrade axios to be aligned with https://github.com/theforeman/foreman/commit/20d7866208b6e33e15f2985da8b6b8a9e3906bec
Tested locally with luna-forklift
=> chore(axios): upgrade axios to v^0.19.0

packages/vendor-core/README.md, packages/vendor-core/lib/VendorModule.js, packages/vendor-core/lib/customModules/jquery.js, packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json, packages/vendor-core/scss/vendor-core.scss, packages/vendor-dev/babel.preset.js, packages/vendor-dev/lib/resolveBabelPath.js, packages/vendor-dev/package-lock.json, packages/vendor-dev/package.json, packages/vendor/package-lock.json
Fix the custom modules for dev env.
Use `babel-plugin-module-resolver` instead of `babel-plugin-transform-rename-import` to support custom modules in development mode.
Tested locally against foreman.
=> fix(CustomModules): Fix custom modules in vendor-dev

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
upgrade diff to version ^4.0.1 so it will be compatible with: https://github.com/theforeman/foreman/commit/7d38537102a30350c5e1ae58c07cdeb903681095#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
Locally against luna-env.
=> chore(vendor-core): upgrade diff to version ^4.0.1

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Adds [react-router-bootstrap](https://github.com/react-bootstrap/react-router-bootstrap) to resolve packagin issues for plugins.
It used in:
https://github.com/theforeman/foreman-tasks/blob/master/package.json#L74
https://github.com/Katello/katello/blob/master/package.json#L76
In luna env.
=> chore(vendor-core): adds react-router-bootstrap

packages/vendor-core/package-lock.json, packages/vendor-core/package.json, packages/vendor/package-lock.json, packages/vendor/package.json
Upgrade lodash to fix vulnerability:
https://snyk.io/vuln/SNYK-JS-LODASH-73638
luna env.
=> chore(lodash): upgrade lodash to v^4.17.14

package-lock.json, package.json
Upgrade eslint to version 6
Locally
=> chore(root): upgrade eslint

.github/issue_template.md, .github/pull_request_template.md
Update the Github PR and issues templates.
=> docs(github): update github templates

.commitlintrc.json, .cz-config.js, .travis.yml, contributing.md, package-lock.json, package.json
Automate the commit process using `commitizen` and `commitlint`.
To create a new commit run:
```sh
git add .
npm run commit
```
NO
NO
=> chore(root): use commitizen and commitlint to automate commits

packages/vendor/scripts/deploy-docs.sh
fix vendor `docs:deploy` for none pr jobs
=> chore(vendor): fix vendor docs:deploy for none prs

packages/vendor/readme.md
Add links to the deployed docs in the vendor readme
=> docs(vendor): add deployed docs to readme

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Add `react-loading-skeleton` package to core
=> add react-loading-skeleton package

.github/issue_template.md, .github/pull_request_template.md
Update the Github Issues and PullRequests templates
=> docs(root): update github issue/pr templates

packages/vendor-core/package-lock.json, packages/vendor-core/scss/vendor-core.scss
=> Expose stylesheets for loading-state

packages/vendor-dev/package.json, packages/vendor-dev/scss/mixins.scss, packages/vendor-dev/scss/variables.scss, packages/vendor-dev/scss/vendor-dev.scss
expose `scss` folder pointing to `vendor-core` so consumers of `vendor-dev` can use `scss`.
ISSUES: fixes #GH-39, refs #27531
=> feat(vendor-dev): expose scss folder pointing to vendor-core

contributing.md, packages/vendor-core/README.md, packages/vendor-dev/README.md, packages/vendor/readme.md, readme.md, roadmap.md
add `roadmap.md` for root and sub-packages to make the roadmap transparent.
=> docs(root): add roadmap.md for root and sub-packages

packages/vendor-core/package-lock.json, packages/vendor-core/package.json, packages/vendor-dev/package-lock.json, packages/vendor/package-lock.json
=> feat(vendor-core): bump patternfly-react

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Adding a package implementing drag & drop support.
=> feat(vendor-core): add D&D react library

scripts/publish-github-ci.sh
Update the lock files when publishing a new version
=> fix(root): update lock files on publish

packages/vendor-core/package.json
Update react to version >= 16.9.0
Notice we already uses react 16.9.0 in the dist.
=> feat(vendor-core): update react to version >= 16.9.0

package-lock.json, package.json
Updating Lerna should fix the issue when lerna skips the creation of GitHub releases.
The feature was written using an older version of `lerna` while reading the new docs versions.
See:
- https://github.com/lerna/lerna/commit/4974b78
- https://github.com/lerna/lerna/issues/2177
- https://github.com/lerna/lerna/commit/a3d264e
=> fix(root): create github releases when versioning

scripts/.githooks/pre-commit
only update lock files when CI, not PR, and in theforeman/foreman-js#master
=> fix(root): update lock files before deploy

.travis.yml, scripts/post-publish-comment-github.sh
=> feat(root): after deploy - comment on each pr included in the release

.cz-config.js, packages/env/README.md, packages/env/babel/index.js, packages/env/package-lock.json, packages/env/package.json, packages/vendor-core/package-lock.json
Adds a new package called `@theforeman/env`
The `env` package should bring a development environment for foreman core and plugins.
https://github.com/theforeman/foreman/pull/7178
=> WIP: adds env pkg with babel

.github/pull_request_template.md, packages/env/README.md, readme.md, roadmap.md
=> docs(env): update docs relevant to env

.travis.yml
fix github comment after deploy
=> fix(root): fix github comment after deploy

.cz-config.js, .github/pull_request_template.md, packages/babel/README.md, packages/babel/index.js, packages/babel/package-lock.json, packages/babel/package.json, packages/env/README.md, packages/env/package.json, packages/vendor-core/package-lock.json, packages/vendor-dev/package-lock.json, packages/vendor/package-lock.json, readme.md, roadmap.md
Move the babel configurations to a standalone package
=> feat(babel): adds babel package

packages/babel/README.md
Fix the babel installation docs.
=> docs(babel): fix the babel readme doc

.cz-config.js, .github/pull_request_template.md, packages/builder/README.md, packages/builder/bin/tfm-build.js, packages/builder/bin/tfm-builder-analyze.js, packages/builder/bin/tfm-builder-install.js, packages/builder/bin/tfm-dev-server.js, packages/builder/package.json, readme.md
adds a skeleton project for `@theforeman/builder`
the main content here is documentations and dummy scripts that will explain the general design of this package
=> docs(builder): adds a skeleton project for @theforeman/builder

packages/builder/babel/presets.js
Attempt to fix the build error here:
https://ci.theforeman.org/job/test_develop_pr_core/2881/database=postgresql-integrations,ruby=2.5,slave=fast/console
https://github.com/theforeman/foreman/pull/7178
=> fix(builder): syntax error in presets catch

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
- v5 is fully backwards compatible with 4.x so **no need to upgrade our primary version**.
The only reason for the major version bump has to do with how they were specifying dependencies in react-router-dom.
- v5 introduces several structural improvements, including:
Better support for React 16
Eliminates all warnings in <StrictMode>
New context API (internal only)
Fully automated releases
- v5 also introduces a few new features
Read more about it in https://reacttraining.com/blog/react-router-v5/
=> feat(vendor-core): bump react-router-dom

scripts/post-publish-comment-github.sh
Fix the commenting on the deployed pr after merge and deploy
=> fix(root): comment on github PRs after npm deploy

.cz-config.js, .github/pull_request_template.md, packages/eslint-plugin-foreman/README.md, packages/eslint-plugin-foreman/bin/tfm-linter.js, packages/eslint-plugin-foreman/lib/index.js, packages/eslint-plugin-foreman/lib/src/linter.js, packages/eslint-plugin-foreman/package-lock.json, packages/eslint-plugin-foreman/package.json, readme.md, roadmap.md
Creating an opiniated styiling for core and plugins
ISSUES: refs #28393
=> feat(eslint-plugin-foreman): adding eslint plugin

packages/eslint-plugin-foreman/lib/index.js, packages/eslint-plugin-foreman/lib/src/linter.js, packages/eslint-plugin-foreman/lib/src/recommended.js, readme.md
=> fix(eslint-plugin-foreman): adding recommended config

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Add connected-react-router to use it as one source of truth for plugins as for none-react pages.
=> feat(vendor-core): add connected-react-router

packages/eslint-plugin-foreman/index.js, packages/eslint-plugin-foreman/lib/src/linter.js, packages/eslint-plugin-foreman/package.json
=> fix(eslint-plugin-foreman): add main to package-json

packages/eslint-plugin-foreman/bin/tfm-linter.js, packages/eslint-plugin-foreman/lib/src/linter.js, packages/eslint-plugin-foreman/lib/src/recommended.js, packages/eslint-plugin-foreman/package-lock.json, packages/eslint-plugin-foreman/package.json
=> Add fix option to eslint cli

packages/eslint-plugin-foreman/lib/src/linter.js, packages/eslint-plugin-foreman/lib/src/recommended.js, packages/eslint-plugin-foreman/package-lock.json, packages/eslint-plugin-foreman/package.json
=> fix(eslint-plugin-foreman): adding react-hooks rules

package-lock.json, packages/env/README.md, packages/env/package-lock.json, packages/env/package.json, packages/env/test/.babelrc.js, packages/env/test/bin/tfm-test.js, packages/env/test/config.js, packages/env/test/jestPreprocess.js, packages/env/test/test_setup.js, packages/vendor/vendor-webpack-plugin/createWebpackExternals.js
=> feat(env): adding jest

package-lock.json
=> fix(root): fix autodeploy - revert package-lock.json

packages/eslint-plugin-foreman/README.md
=> fix(env): Add executable permission to tfm-test

packages/env/helpers/index.js, packages/env/package.json, packages/env/test/.babelrc.js, packages/env/test/config.js, packages/env/test/jestPreprocess.js, packages/vendor-dev/lib/resolveBabelPath.js
=> Add coverage support

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
patternfly fixed the modal issue after react-bootstrap upgrade
ISSUES: #28391
=> feat(vendor-core): update patternfly-react to v2.39.10

packages/builder/babel/presets.js, packages/env/bin/tfm-test.js, packages/env/package-lock.json, packages/env/package.json, packages/env/test/.babelrc.js, packages/env/test/babel.config.js, packages/env/test/config.js, packages/env/test/jestPreprocess.js
=> fix(env): fix tfm-test script

packages/env/test/babel.config.js
=> fix(env): fix babel importing

packages/stories/README.md
=> docs(stories): explain how to disable a centered story

packages/stories/README.md, packages/stories/package-lock.json, packages/stories/package.json, packages/stories/src/config/addons.js, packages/stories/src/config/config.js, packages/stories/src/config/decorators/centered.js, packages/stories/src/config/decorators/index.js, packages/stories/src/config/parameters/docs.js, packages/stories/src/config/parameters/index.js, packages/stories/src/config/webpack/webpack.config.rules.js, packages/stories/src/index.js
Adding [@storybook/addon-docs](https://github.com/storybookjs/storybook/tree/next/addons/docs)
1. Adds a `DocsPage` for each story, see: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md
2. Support writing stories using `.stories.mdx` files, see: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md
=> feat(stories): adds @storybook/addon-docs

packages/stories/README.md, packages/stories/src/config/parameters/index.js, packages/stories/src/config/services/sorting.js
=> feat(stories): support sorting stories

.eslintrc, packages/builder/.eslintignore, packages/builder/.eslintrc, packages/builder/package.json
=> fix(builder): add eslint

packages/test/bin/tfm-publish-coverage.js, packages/test/package-lock.json, packages/test/package.json
=> fix(test): fix coveralls script

packages/eslint-plugin-foreman/lib/src/linter.js
When there are errors that cannot be auto-fixed,
we exit too early and files are not changed
for errors that can be fixed.
Steps to reproduce:
1) have at least one auto-fixable linting offence (missing semicolon) and non-auto-fixable (dependencies not declared in package.json)
2) run tfm-lint and see offences
3) run with `--fix`, only non-fixable offences remain
4) run without `--fix`, the output is same as in step 2. Run git status to see no files were auto-fixed.
=> fix(eslint-plugin-foreman): write to files on --fix flag

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json, roadmap.md
=> refactor(vendor-core): remove redux-form from vendor-core

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Allows adding head's tags directly from react component
=> feat(vendor-core): adding React Helmet

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json, packages/vendor-core/scss/variables.scss, packages/vendor-core/scss/vendor-core.scss, packages/vendor/bundle/webpack.config.js, packages/vendor/package-lock.json, packages/vendor/package.json, packages/vendor/vendor-webpack-plugin/Manifest.js, packages/vendor/vendor-webpack-plugin/vendor-webpack-plugin.js
Adds patternfly v4 styles and core components.
=> feat(vendor-core): adds patternfly v4

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
This adds `@patternfly/react-table`, which is part of the patternfly 4 react packages
no
=> Adds @patternfly/react-table

packages/vendor-core/package-lock.json, packages/vendor-core/package.json, roadmap.md
The change is required because of this pr: https://github.com/novnc/noVNC/pull/1262 is required in  order to add the kubevirt console and unforchantly novnc releasing a version once a year, and they are not planning on releasing a new version soon
The link for kubevirt console issue:
https://projects.theforeman.org/issues/27320
https://github.com/theforeman/foreman/pull/6907
=> feat(vendor-core): change in order to have kubevirt console

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
=> feat(vendor-core): adds @patternfly/react-icons

packages/vendor-core/lib/modules.js, packages/vendor-core/package.json
ISSUES: refs #29298
This is needed for patternfly 4. It is already used in Katello in https://github.com/Katello/katello/commit/44f712016f8c6c873b7daec4f158dc2a0bd9b48a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R61 - with this we can remove the dependency there.
https://github.com/Katello/katello/commit/44f712016f8c6c873b7daec4f158dc2a0bd9b48a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R61
=> feat(vendor-core): adding patternfly 4 react-tokens

.cz-config.js, .github/pull_request_template.md, README.md, packages/find-foreman/README.md, packages/find-foreman/index.js, packages/find-foreman/package.json, roadmap.md
ISSUES: refs #29905
This is useful in a testing environment when you want to point a testing tool to Foreman's packages rather than duplicate them for testing purposes.
Not using it yet, but the logic is duplicated in https://github.com/Katello/katello/pull/8722 and the idea is to switch to the package.
A follow up change to this is modifying the foreman-eslint plugin to use this package and perhaps also making a jest config plugin that Foreman plugins can automatically use.
=> feat(find-foreman): adds find-foreman package

packages/test/README.md, packages/test/package-lock.json, packages/test/package.json
More info on the package: https://github.com/testing-library/react-testing-library and discussion:
https://community.theforeman.org/t/using-react-testing-library-in-katello/18120
Used in https://github.com/Katello/katello/pull/8644/files
=> feat(test): added react-testing-library to test package

packages/test/src/config.js, packages/test/src/resolveNodeModule.js
=> fix(test): fix tests to work similar using npm or local

.cz-config.js
support the commit message used by dependbot
=> chore(root): support custom scope in commit message

.github/dependabot.yml
=> chore(root): fix dependbot commit message

.github/workflows/ci.yml
The GH action will run on each PR, build foreman-js and link to it from other repos.
=> feat(root): add GH actions to test against foreman & plugins

.github/workflows/ci.yml
=> fix(root): add GH token to the build action

packages/vendor-core/lib/modules.js, packages/vendor-core/package.json
Adds @patternfly/react-styles, the version is from the[ 2020.08 PF release ](https://www.patternfly.org/2020.08/documentation/react/overview/release-notes)
=> feat(vendor-core): adds @patternfly/react-styles

package-lock.json, package.json
run `npm update` (in root) to safely upgrade dependencies.
=> chore(root): run npm update [safe upgrade]

packages/vendor-dev/eslint.extends.js, packages/vendor-dev/package.json
This uses the `findForeman` package to check for dependencies in the eslint config. The benefits of this are:
- Always use the correct path in CI and locally
- Plugins can now use this configuration and all extraneous dependencies are covered in Foreman. `findForeman` will find foreman in a parent, child, or sibling (including itself so it works for foreman) directory. This means it will work in plugins as well as Foreman.
In Katello, we do [this now](https://github.com/Katello/katello/blob/f9a239d4e42ab95dcf2561f372df00d0cb47c42b/webpack/.eslintrc.js#L36). When this PR is added, we won't need to have that config added as it will already be done from extending this config. For plugins that extend this eslint config, the foreman dependencies will be considered for the extraneous …
=> feat(vendor-dev): use find-foreman for eslint extraneous dependencies

scripts/.githooks/pre-commit
Fixes an issue related to the lerna upgrade in https://github.com/theforeman/foreman-js/commit/2ff8ac2650f634128d5e84aebfec143f13f865d9
=> fix(root): update lock files before versioning

.github/workflows/ci.yml, packages/eslint-plugin-foreman/lib/src/linter.js
fix an issue when using with foreman-js:link
=> fix(eslint-plugin-foreman): resolve node_modules from cwd

.github/workflows/ci.yml, CONTRIBUTING.md, package-lock.json, package.json, scripts/link-foreman-js.js
Adds the `link` command so you can easily link the foreman-js packages to your project.
=> feat(root): adds the ability to link foreman-js to your project

package-lock.json, package.json
Updates the following packages to latest:
- @commitlint/cli
- @commitlint/config-conventional
- @commitlint/travis-cli
- commitlint-config-cz
=> chore(root): upgrade commitlint

package.json
add `npm run add` and `npm run add-to-vendor` commands to easily add new packages
=> feat(root): add shortcut command to add dependencies

.github/workflows/build-tarballs.yml, CONTRIBUTING.md
This is a way to test out package changes in PRs without uploading anything to npm. More information below
The best way to test this is to use a PR that upgrades jest on my fork https://github.com/johnpmitsch/foreman-js/pull/14#issuecomment-697498083 - The action is merged into master there so we can test out what a PR upgrading a package would look like with these actions
=> Create tarballs for packages and upload as artifact for PRs

packages/test/package-lock.json, packages/test/package.json
=> feat(test): add @testing-library/react-hooks

.github/workflows/test-with-foreman.yml, .github/workflows/test-with-plugins.yml
Same fix for Foreman was: https://github.com/theforeman/foreman/pull/8209
=> fix(root): install ruby for GH action

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Updates patternfly-react with newer version.
Contains https://github.com/patternfly/patternfly-react/pull/4747 which is needed to fix [#29020](https://projects.theforeman.org/issues/29020)
=> fix(vendor-core): update patternfly-react to 2.39.17

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Adds client packages for graphql which allow
us to fetch data using graphql.
ISSUES: refs #31745
=> feat(vendor-core): add graphql client packages

.eslintignore, package.json, packages/builder/.eslintignore, packages/builder/.eslintrc, packages/builder/package.json, packages/find-foreman/package.json, packages/stories/.eslintignore, packages/stories/.eslintrc, packages/stories/package.json, packages/test/src/helpers/index.js, packages/test/src/test_setup.js, packages/vendor-core/.eslintignore, packages/vendor-core/.eslintrc, packages/vendor-core/package.json, packages/vendor-dev/.eslintignore, packages/vendor-dev/.eslintrc, packages/vendor-dev/package.json, packages/vendor/.eslintignore, packages/vendor/.eslintrc, packages/vendor/package.json, scripts/link-foreman-js.js
Use a global eslint instead of an individual for each sub package. It is faster and give us linting for all packages automatically.
=> chore(root): run eslint globally with one config file

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
=> Add Patternfly 4 react charts

packages/vendor-core/lib/modules.js
To help this: https://github.com/theforeman/foreman/pull/8621
=> feat(vendor-core): adds the brace seach to the react ace editor

packages/test/package-lock.json, packages/test/package.json, packages/test/src/config.js
Adds @apollo/react-testing package which provides
testing utilities for apollo client.
=> feat(test): add @apollo/react-testing

packages/vendor-core/scss/vendor-core.scss
=> feat(vendor-core): add patternfly-addons styles

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
=> feat(vendor-core): add humanize-duration lib

packages/vendor-core/lib/modules.js, packages/vendor-core/package-lock.json, packages/vendor-core/package.json
Was used in the rh_cloud plugin
ISSUES: fixes #33604
=> feat(vendor-core): add react-intl

packages/vendor-core/lib/modules.js
https://github.com/theforeman/foreman/pull/9051#discussion_r793036568
=> fix(vendor-core): add ace-builds/ace to modules

packages/builder/package-lock.json, packages/builder/package.json, packages/stories/package-lock.json, packages/stories/package.json, packages/test/package-lock.json, packages/test/package.json, packages/vendor/package-lock.json, packages/vendor/package.json
foreman testing doesnt work because:
* Cannot find module '..' from 'node_modules/@babel/types/lib/builders/validateNode.js'
* Cannot find module 'cheerio/lib/utils' from 'node_modules/enzyme/build/Utils.js'
=> pinning babel and cheerio

.cz-config.js, .github/workflows/build-tarballs.yml, README.md, packages/eslint-plugin-rules/README.md, packages/eslint-plugin-rules/index.js, packages/eslint-plugin-rules/lib/require-ouiaid.js, packages/eslint-plugin-rules/package-lock.json, packages/eslint-plugin-rules/package.json, roadmap.md
Add eslint-plugin-rules to hold eslint custom rules for Foreman and plugins
=> feat(eslint-plugin-rules): add eslint-plugin-rules

packages/vendor-core/package-lock.json, packages/vendor-core/package.json
pin frontend-component-utilities
=> fix(vendor-core): pin frontend-component-utilities

.github/workflows/build-tarballs.yml, .gitignore, packages/vendor-core/package-lock.json, packages/vendor-core/package.json, packages/vendor/bundle/webpack.config.js, packages/vendor/package.json
=> Test charts before PF5
