packages/vendor/lib/WebpackExportForemanVendorPlugin.js
packages/vendor/lib/createVendorEntry.js
packages/vendor/scripts/webpack-analyze.sh

Fix the issue causing the `npm run analyze` to fail.
It failed from 2 reasons:
1. It uses stdout to write the `stats.json` file so `console.log` statements corrupt the `stats.json`
2. The webpack build failed because it didn't have enough memory

fix(analyze): fix the npm run analyze

---

packages/vendor-core/package-lock.json
packages/vendor/lib/Manifest.js
packages/vendor/package.json
packages/vendor/readme.md
packages/vendor/webpack.config.js
packages/vendor/webpack.plugin.js

Builds development and production dist files.
See #4 
This PR do 2 things:
1. When running `npm run build` it will create 2 different builds and 2 different `manifest.json` into the `dist` folder so my dist folder now looks as well:
```sh
packages/vendor/dist
├── foreman-vendor.bundle-v0.1.0-alpha.4-development-e226acdcab8caadcc978.css
├── foreman-vendor.bundle-v0.1.0-alpha.4-development-e226acdcab8caadcc978.css.gz
├── foreman-vendor.bundle-v0.1.0-alpha.4-development-e226acdcab8caadcc978.css.map
├── foreman-vendor.bundle-v0.1.0-alpha.4-development-e226acdcab8caadcc978.css.map.gz
├── foreman-vendor.bundle-v0.1.0-alpha.4-development-e226acdcab8caadcc978.js
├── foreman-vendor.bundle-v0.1.0-alpha.4-development-e226acdcab8caadcc978.js.gz
├── …
```

Fixes #4 - Build development and production

---

.travis.yml
package.json
packages/vendor-core/vendor-core
packages/vendor-dev/package-lock.json
packages/vendor-dev/vendor-dev
packages/vendor/package-lock.json
packages/vendor/vendor

Stop using `lerna link` as it is not useful.
See #7 about the issue with `lerna link`
Remove the option to use `lerna link` as we should not use it.
Tested locally:
```sh
cd foreman-js
npm install
npm run link
npm run build
npm run clean
npm install
npm run build
```
To search for react instances in the build result, search inside the `js` file for the term: `@license React`.

Fixes #7 - remove npm run link

---

packages/vendor-dev/README.md
packages/vendor-dev/babel.preset.js

Stop using `NODE_ENV` in babel so the consumer will decide on what env to use `foreman-dev/babel`.
Locally in a luna env.

fix(vendor-dev-babel): stop using NODE_ENV in babel

---

packages/vendor-core/lib/modules.js
packages/vendor-core/package-lock.json
packages/vendor-core/package.json

Add support for webcomponents in foreman.
Adds webcomponents and webcomponents polyfills. As I do not understand webpack, I believe some closer look could be needed. @sharvit? :) 
Locally with theforeman/foreman#6735

feat(vendor-core): add webcomponents polyfills

---

packages/vendor-core/package-lock.json
packages/vendor-core/package.json

react-bootstrap update cause tests to fail, until it will be resolved we should use more stable
version of patternfly-react

fix(vendor-core): pin patternfly-react after react-bootstrap update

---

packages/eslint-plugin-foreman/index.js

Plugin's config shouldn't override core's config

fix(eslint-plugin-foreman): fix plugin config

---

packages/env/package.json

Remove the `tfm-test` from the package bin since the file `./bin/tfm-test.js` does not exist.

fix(env): remove tfm-test from package bin

---

packages/vendor-core/package-lock.json
packages/vendor-core/package.json

After upgrating react-router-dom v5 it broke react-router-bootstrap

feat(vendor-core): bump react-router-bootstrap

---

packages/env/test/babel.config.js
packages/env/test/config.js
packages/env/test/jestPreprocess.js

Hopefully this workaround (taken from [here](https://github.com/theforeman/foreman/pull/7233/files#diff-14e6781502e896261c0a151f0600e9e0R33)) would work. it works locally :pray:

fix(env): use babel-jest transfom workaround for babel config

---

packages/stories/src/config/webpack/webpack.config.rules.js

Apply `MDX` on all `*.mdx` instead of `*.stories.mdx`.
`*.stories.mdx` files will continue to get loaded automatically as stories while `*.mdx` won't.

fix(stories): use mdx-loader on all mdx files

---

packages/test/package-lock.json
packages/test/package.json

There is an issue with cheerio v1, downgrading

fix(test): force enzyme to use cheerio@0.22.0

---

packages/builder/babel/presets.js

In order to prevent webpack to do tree-shaking, set modules to commonjs.
ISSUES: refs #28857

fix(builder): update babel-env to transform modules to commonjs

---

packages/test/src/helpers/index.js

Additional '--' is no longer needed for tfm-test to recognize path to test files.
ISSUES: fixes #GH-115
https://github.com/theforeman/foreman-js/issues/115

fix(test): fix running tests for individual files

---

packages/builder/package-lock.json
packages/builder/package.json

ISSUES: refs #29605
pin @babel/preset-env to v7.9.5 and babel-plugin-dynamic-import-node to v2.3.0
to make dynamic imports for react-intl work.

fix(builder): pin @babel/preset-env to 7.9.5

---

packages/vendor-core/package.json

This library should be exist in pf3
but after the pf4 upgrade it was not available
It should fix the issue in foreman, when testing the AutoComplete component.
Should not affect production.

fix(vendor-core): adds react-bootstrap-typeahead

---

packages/test/src/config.js
packages/test/src/resolveNodeModule.js
packages/test/src/test_setup.js
packages/vendor-core/package.json

fix the way we are resolving npm modules in jest

fix(test): fix the module resolving

---

.github/workflows/test-foreman-js.yml
.github/workflows/test-with-foreman.yml
.github/workflows/test-with-plugins.yml

Refactor the `ci.yml` and split to multiple files.
Also, adds an option to the plugin tests matrix to test with or without foreman.
Many parts of the code are copied between yml files which is not a good practice but the best gh-actions can give us for now.
We might be able to share workflows only if we will implement them in javascript (that's what I understand from the gh-actions docs).

refactor(root): refactor gh-actions to multiple files

---

.github/workflows/test-with-plugins.yml
packages/find-foreman/README.md
packages/find-foreman/index.js
packages/vendor-dev/eslint.extends.js

fix an issue when ../foreman/package.json must be presented to be able to run lint

fix(eslint-plugin-foreman): allow linting plugins without foreman

---

packages/vendor-core/lib/modules.js
packages/vendor-core/package-lock.json
packages/vendor-core/package.json

feat(vendor-core): adds rc-number-input

---

.github/pull_request_template.md

use a simpler pull-request template as most of the information exists
in the commit-message, if used properly with `npm run commit`.

chore(root): simplify the pr template

---

packages/vendor/scripts/deploy-docs.sh

The doc links in the vendor readme are outdated, see:
https://github.com/theforeman/foreman-js/tree/master/packages/vendor#what-you-get-with-this-project
It used to deploy to subdomain with the version suffix `theforeman-vendor-docs-v4-14-2` while the readme point to `theforeman-vendor-docs`.
Simplify the vendor deploy-docs script, always deploy to `theforeman-vendor-docs` and remove things that never worked.

docs(vendor): upload docs to the right domain

---

packages/vendor-core/package-lock.json
packages/vendor-core/package.json
packages/vendor/bundle/webpack.config.js

upgrade patternfly-react-extensions to v3.0.12 so both
patternfly-react and patternfly-react-extensions
would pull the same react-bootstrap version

feat(vendor-core): upgrade pf3-extensions v3.0.12

---

packages/vendor-core/lib/modules.js

Seems like we are using it but it is not exported properly.
It used to work because we don't directly import it in production but we do in test files so it is needed.

fix(vendor-core): export select2

---

packages/test/package-lock.json
packages/test/package.json
packages/test/src/helpers/index.js

Upgrades jest package. Note that jest-cli provides jest. This is needed by react-testing-library https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0

chore(test): Upgrades Jest

---

.commitlintrc.json

Dependabot will create the commit body automatically and it sometimes is long. I don't see a big
issue disabling this since the commit body wraps most places

chore(root): disable max length for commit message body

---

packages/vendor-core/lib/modules.js

Make sure apollo is exported from vendor.
Currently, linting gives me `import/no-extraneous-dependencies` complaining apollo is not in foreman's deps:
`'@apollo/client' should be listed in the project's dependencies. Run 'npm i -S @apollo/client' to add it`

fix(vendor-core): export apollo from vendor

---

packages/vendor-core/lib/modules.js

This is needed to fix the current packaging failure from my testing.
```
+ scl enable tfm '
webpack --bail --config config/webpack.config.js
'
ModuleNotFoundError: Module not found: Error: Can't resolve '@apollo/client/link/batch-http' in '/builddir/build/BUILD/foreman-2.5.0-develop/webpack/assets/javascripts/react_app/Root'
at factoryCallback (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/Compilation.js:282:40)
at factory (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
at resolver (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
at asyncLib.parallel (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
at …
```

fix(vendor-core): export apollo/client/link/batch-http from vendor

---

packages/builder/babel/plugins.js

We are using optional chaining, but we do not include this in babel plugins, so on nodejs 10 this is
failing to build.

fix(builder): optional chaining in builder

---

packages/builder/babel/plugins.js

Explicitly declare the plugin-syntax-optional-chaining babel plugin
as well to ensure it is loaded.
Testing this in a build environment, I was seeing better results. Testing this change locally in our build environment is being difficult. So if this change is OK, it would be helpful to include it, get a new build on NPM and then test RPM builds.

fix(builder): syntax optional chaining in builder

---

packages/vendor-core/lib/modules.js
packages/vendor-core/package-lock.json
packages/vendor-core/package.json

part of the RFC in https://community.theforeman.org/t/rethinking-react-redux-folder-structure/24183
ISSUES: Fixes #32903

feat(vendor-core): add @reduxjs/toolkit library

---

.github/workflows/test-with-plugins.yml

The rh-cloud plugin isn't fully tested with foreman's latest branch, removing it now as tests are
failing.

refactor(root): remove rh-cloud plugin test

---

packages/vendor-core/package-lock.json
packages/vendor-core/package.json

Bump react-table version so we can use the draggable icon/button for table rows

feat(vendor-core): bump react-table version

---

packages/eslint-plugin-foreman/lib/src/core.js

The Javascript `for...of` loop syntax is better than `Array.prototype.forEach` in many situations.
```js
for (const apple of apples) {
if (apple.bad) continue;
polishApple(apple);
}
```
Unlike `for...in` loops which are old-style Javascript and only work on objects, `for-of` is modern Javascript and works on any iterable, including arrays, objects,  sets, strings, etc.
Github actually has an eslint rule that _prohibits_ `forEach`, and they extensively outline why `for-of` is better in their [eslint-plugin-github documentation](https://github.com/github/eslint-plugin-github/blob/main/docs/rules/array-foreach.md), which I highly recommend reading.
For me this is more about having readable code than performance optimization.
I don't think we need to go as far as requiring it, but I do think …

feat(eslint-plugin-foreman): allow for-of loops

---

packages/vendor-core/lib/customModules/jquery.js
packages/vendor-core/package-lock.json
packages/vendor-core/package.json

We don't need flot charts anymore as we use React components only.
BREAKING CHANGE: The flot.jquery has been dropped and can be no longer used.
Core PR to drop the uses: https://github.com/theforeman/foreman/pull/8522

refactor(deps): drop flot.jquery library

---

packages/vendor-core/scss/vendor-core.scss

We've been getting the error: `Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '@redhat-cloud-services/frontend-components/index.css'`
adding it to our styles `vendor-core.scss` should fix it.

Add styles of @redhat-cloud-services

---

packages/stories/src/config/webpack/webpack.config.vendor.js

got an error when trying to run storybook from Foreman: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of
undefined
ISSUES: fixes #393

fix(stories): handle templateParameters as a promise

---

packages/test/src/resolveNodeModule.js

require.resolve Doesn't know how to handle `import * from '..'` (`'..'` is the issue). The jest defaultResolver does know.
`require.resolve` was added here: https://github.com/theforeman/foreman-js/pull/148

fix(test): fix custom jest resolver

---

packages/test/bin/tfm-test.js
packages/test/package-lock.json
packages/test/package.json
packages/test/src/helpers/index.js

tests use the newest version of the package it can find, and because `webpack-bundle-analyzer` got auto updated, it installs `commander` v7, which doesn't support optionFor.
before: 
running tests with options will fail.
example: `npm test -- webpack/assets/javascripts/react_app/components/Layout/components/ImpersonateIcon/ImpersonateIcon.test.js -u`
```
foreman-js/packages/test/src/helpers/index.js:43
if (cli.optionFor(rawArg)) {
^
TypeError: cli.optionFor is not a function
at foreman-js/packages/test/src/helpers/index.js:43:19
at Array.filter (<anonymous>)
at remainingArgs (foreman-js/packages/test/src/helpers/index.js:30:10)
at Object.<anonymous> (foreman-js/packages/test/bin/tfm-test.js:30:35)
```

fix(test): updates commander from v4 to v7

---

packages/vendor-core/lib/modules.js
packages/vendor-core/package-lock.json
packages/vendor-core/package.json

This package is not used anywhere.
BREAKING CHANGE:
Removes patternfly/react-catalog-view-extension

feat(vendor-core): remove patternfly/react-catalog-view-extension

---

packages/builder/package-lock.json
packages/builder/package.json
packages/vendor/package-lock.json
packages/vendor/package.json

Had to add `@babel/plugin-proposal-optional-chaining` as it was not being install as part of `babel/preset-env` anymore

chore(builder): bump babel/preset-env
